[tool.poetry]
name = "notes-to-self"
version = "0.0.1"
description = "A blog of sorts"
authors = ["Tom Goren <tom@tomgoren.com>"]

[tool.poetry.dependencies]
python = ">=3.8.2"
pelican = "^4.2.0"
markdown = "^3.2.2"
